# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

def shared_pods
    
    use_frameworks!
    pod 'RxSwift'
    pod 'Boomerang', :git => "https://github.com/synesthesia-it/Boomerang.git", :branch => “v1”
    pod 'LoremIpsum'    pod 'pop'
    pod 'MBProgressHUD'
    pod 'SpinKit'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SnapKit', '~> 3.0.2'
    pod 'Localize-Swift'
    pod 'DateToolsSwift’
    pod 'Action', :git => "https://github.com/RxSwiftCommunity/Action.git"
    pod 'MZFormSheetPresentationController'

    
end

target '' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
end
